name = "proactive-physiotherapy"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "proactive-db"
database_id = "2e1d6e0c-86a0-424f-a04c-ca6db8d5e30f"
